language: python
python:
  - '3.6'
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n
    '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}'
    | xargs wget
  - sudo dpkg -i hugo*.deb
  - pip install Pygments
  - rm -rf public 2> /dev/null
script:
  - hugo
deploy:
  - provider: s3
    access_key_id: AKIAIIORSR4VN3YQY2YQ
    secret_access_key:
      secure: p8uHkcgIoVpmTIJmaFTNeO9EHZ6sQHPrlA93IdDE7RJ1T+OfABdyIXdkTzjIUC/x/Hsj+0CjqjtV8CAzSpANvQe7R/O415FMKhqIAk5yLyLZcKb8tT2ZkRS37rUHqHC6M4N41Saax61mCApLAr4OPy45wANQgmOCPXmozbN9Nh5udrImrBrAsAeM92USxfcYV4KXqAuo9+oFrB96m9jWO3sepyM1mmbz2J7dXB7EkuwdkWhSQZH9Rn3wy5aXO1uShABEx/AqtduWPTQzN484JzsC39j0hWZbOTR2VWgnayda/bn7F34Pz3IGK7zf5iBmskxP4Ekc+SatjM8i2eJMCN6XEiQFRzPEE2On/5fQ9JKFEP/4xrOa9DEXAavvWh/V+YKhgUE0S3yn5bM8BvymYaPoXBFfpX9dOw4r97UK7w1JEyDgx18mZO8fNr8W6woBgJO4E9MFTq/7mR+cAQBGy6DCVVpgeFpuvnDJ24vugP5qbfR85DzMZHKdaOsDqyxsv7Uiamb4B/k2ihHUznmpjkgeXb2y7k96MPiy0oKKGrMZfPSmbKDDca1ZZLDJSdPElKNmlCQ5/mwnPE595qIv5MQ78MnmcQSLtkn8y74GDjvKmfwFEAP4O7b8r8ogaK6V5KYNwZPYE5MUZy2SyfjJjJMJCfNz+ACuu1UwRyqf4o0=
    bucket: rovercode-user-docs
    local_dir: public
    acl: public_read
    skip_cleanup: true
    region: us-east-2
    on:
      repo: rovercode/user-docs
      branch: master
notifications:
  slack:
    secure: UFJU+UvLQD/BdIUnR+ntmVDwtDn5iN3eNhnKlDky+13AEmceXd7R47XujYOmVZ9yNns8LJiR1585SKwi0OrIKjAe2Ja6wTn8kDzrCHcaLiA6w89ogqbeIYACz+EmDP2c1N9YSIkylZRMVz44aZrit2K8bpj/lMaYCWaiWElVoSm7szmbEIMoBZpfPpVkvngadsIHx6oFJlN4BZQTa/CwG/xfC3CFHtViSGbW9B+515ihQvE/w8k6COpSFd6wxVvUcBWKuIdwmokmYfF0eLd6TMOua+ogcyu6EP2qtHl4K2EWRth43QFW2TXjtz682m0uir9uIiqKfFZMCVvEBueRMYDHj4LFcA5z/btBcE9PqN/E7Ar6j8ZEV3qa+jqQe/42+ey97zl6dCLL9ksxFqno3MRTzIWH34QEyPqHN3HxtkLpfEy267OtNfMUFm0I85GGBn9G2xpF32bsqkYksxx9Fxq1ytjaukxVdseN/oVR0G0nnXrCr0/qL2Ixxp7OhGICCNc+eNwPH29P84sMfPdZ3NiZ8+Gyp8KCFHPdKgUPAz1nGp1Gz1JX6J6QeygHOFQ1raOsPdcd4LI4QjjiLTlGoAox6iM+s+JjEc7sWOhfVlFMXjp4162O4xKZ6Tes5BbV6THdNnoQvBZ4LVJaz1gJW1ONqZT2r+sGmamAjlR/U9o=
