language: python
python:
  - '3.6'
install:
  # install latest release version
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}' | xargs wget
  - sudo dpkg -i hugo*.deb
  - pip install Pygments
  - rm -rf public 2> /dev/null
script:
  - hugo
deploy:
  - provider: s3
    access_key_id: AKIAIIORSR4VN3YQY2YQ
    secret_access_key:
      secure: emyN/uB9WXzV0dviD3Fi9toM2oKkUX0IhRJ0vToH6KvFkX6MEmCTmtKAAFXe+Lhw8boujWg4+t0S3zt82z57NLN9f/9SB4JlFidtB+/9BJS/AbUgj+bFP3u2lMqUf0u09AfIFIw/gyO2TidWXrBeoF9JflquS+80lhBsDDIlKkG6M76oGZX/qHKbVW62j2tNX9XEhUuGC8AVguj73qHGQeqhi3u4ohFAsSc0K4I0jbzUHn6LX89jX9lx8iXXxsI+lbOdAe6HIjVRfpwiYp5QVYqJydVqzlo5jJ0YCzYCUAZbTsDesUmVBIZ+Atj1K12mr7fz1z4qe37WSFuDFPChLNKFEEsco28gM4EOR+Ff8FHJEpL+aDBrBrsG3I0nrV25whwnwdYHeDp6+m76WvQ6LWtC82OnBik+khwdi4nsi9WUBXbuiMpcGrcxRsN5b5Jt97twKIHs6Hfdtp9xXLeTxxWtacGpd1KnCyDEjazuWBtwgb9AMUD/C0s/1xvoHN9+DAlDPe4DpNz99WYq1iDybCL575aAjsiXvYHUtweu7IBL5SykfAnvCb4Iqk3+xqSrMtM37LJGtgu2ZSt1DlQGSgysG8R6F6ey+QpqiqzuQN4S89sWEtw6eHL+zvN6lKOKLSZhh+XlRWcDPCQWzM6zo+KAKsDIdZyXdPi+IWCIzHQ=
    bucket: rovercode-user-docs
    local_dir: public
    acl: public_read
    skip_cleanup: true
    region: us-east-2
    on:
      repo: rovercode/user-docs
      branch: master
notifications:
  slack:
    secure: UFJU+UvLQD/BdIUnR+ntmVDwtDn5iN3eNhnKlDky+13AEmceXd7R47XujYOmVZ9yNns8LJiR1585SKwi0OrIKjAe2Ja6wTn8kDzrCHcaLiA6w89ogqbeIYACz+EmDP2c1N9YSIkylZRMVz44aZrit2K8bpj/lMaYCWaiWElVoSm7szmbEIMoBZpfPpVkvngadsIHx6oFJlN4BZQTa/CwG/xfC3CFHtViSGbW9B+515ihQvE/w8k6COpSFd6wxVvUcBWKuIdwmokmYfF0eLd6TMOua+ogcyu6EP2qtHl4K2EWRth43QFW2TXjtz682m0uir9uIiqKfFZMCVvEBueRMYDHj4LFcA5z/btBcE9PqN/E7Ar6j8ZEV3qa+jqQe/42+ey97zl6dCLL9ksxFqno3MRTzIWH34QEyPqHN3HxtkLpfEy267OtNfMUFm0I85GGBn9G2xpF32bsqkYksxx9Fxq1ytjaukxVdseN/oVR0G0nnXrCr0/qL2Ixxp7OhGICCNc+eNwPH29P84sMfPdZ3NiZ8+Gyp8KCFHPdKgUPAz1nGp1Gz1JX6J6QeygHOFQ1raOsPdcd4LI4QjjiLTlGoAox6iM+s+JjEc7sWOhfVlFMXjp4162O4xKZ6Tes5BbV6THdNnoQvBZ4LVJaz1gJW1ONqZT2r+sGmamAjlR/U9o=
